/* eslint-disable */
// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

const indexRoute = createFileRoute("/")();
const studioRoute = createFileRoute("/studio")();
const voicesRoute = createFileRoute("/voices")();
const historyRoute = createFileRoute("/history")();
const settingsRoute = createFileRoute("/settings")();

const rootRoute = createFileRoute("__root")();

export const routeTree = rootRoute.addChildren([
  indexRoute,
  studioRoute,
  voicesRoute,
  historyRoute,
  settingsRoute,
]);
